In [1]:
import pandas as pd

In [17]:
hospital_df = pd.read_csv("/Users/jeffreyj/Documents/GitHub/data-science-essentials-4/data/Hospitals.csv")

The starting index begins from 0; the ending index terminates at len(pd)+1

There are 7596 rows and 34 columns

In [18]:
print(hospital_df)

                 X             Y  OBJECTID         ID  \
0    -1.331889e+07  4.346975e+06         1    5793230
1    -1.322651e+07  4.049626e+06         2   53391362
2    -1.315620e+07  4.031978e+06         3   11190023
3    -1.317190e+07  4.041752e+06         4   17090028
4    -1.313208e+07  4.037270e+06         5   23691706
...            ...           ...       ...        ...
7591 -8.566905e+06  4.728815e+06      7607  183520904
7592 -1.219624e+07  3.676931e+06      7608  192185607
7593 -8.084677e+06  5.094112e+06      7609  196706457
7594 -8.522423e+06  4.718512e+06      7610  191021401
7595 -1.244921e+07  4.976468e+06      7611  196784108

                                                   NAME  \
0                       CENTRAL VALLEY GENERAL HOSPITAL
1     LOS ROBLES HOSPITAL & MEDICAL CENTER - EAST CA...
2                     EAST LOS ANGELES DOCTORS HOSPITAL
3             SOUTHERN CALIFORNIA HOSPITAL AT HOLLYWOOD
4                         KINDRED HOSPITAL BALDWIN PARK
...                                                 ...
7591      ADVENTIST HEALTHCARE WHITE OAK MEDICAL CENTER
7592          COPPER QUEEN DOUGLAS EMERGENCY DEPARTMENT
7593                          WHITING FORENSIC HOSPITAL
7594                 J KENT MCNEW FAMILY MEDICAL CENTER
7595                      UNIVERSITY ORTHOPAEDIC CENTER

                         ADDRESS             CITY STATE    ZIP           ZIP4  \
0        1025 NORTH DOUTY STREET          HANFORD    CA  93230  NOT AVAILABLE
1                 150 VIA MERIDA  WESTLAKE VILAGE    CA  91362  NOT AVAILABLE
2        4060 WHITTIER BOULEVARD      LOS ANGELES    CA  90023  NOT AVAILABLE
3         6245 DE LONGPRE AVENUE        HOLLYWOOD    CA  90028  NOT AVAILABLE
4      14148 FRANCISQUITO AVENUE     BALDWIN PARK    CA  91706  NOT AVAILABLE
...                          ...              ...   ...    ...            ...
7591           11890 HEALING WAY    SILVER SPRING    MD  20904  NOT AVAILABLE
7592           100 E. 5TH STREET          DOUGLAS    AZ  85607  NOT AVAILABLE
7593                70 OBRIEN DR       MIDDLETOWN    CT   6457           3945
7594  175 HARRY S TRUMAN PARKWAY        ANNAPOLIS    MD  21401  NOT AVAILABLE
7595              590 WAKARA WAY   SALT LAKE CITY    UT  84108  NOT AVAILABLE

      ...             VAL_DATE  \
0     ...  2014/02/10 00:00:00
1     ...  2014/02/10 00:00:00
2     ...  2014/02/10 00:00:00
3     ...  2014/02/10 00:00:00
4     ...  2014/02/10 00:00:00
...   ...                  ...
7591  ...  2020/05/05 00:00:00
7592  ...  2020/05/05 00:00:00
7593  ...  2020/05/08 00:00:00
7594  ...  2020/05/05 00:00:00
7595  ...  2020/05/05 00:00:00

                                                WEBSITE       STATE_ID  \
0                          http://www.hanfordhealth.com  NOT AVAILABLE
1                      http://www.losrobleshospital.com  NOT AVAILABLE
2                                 http://www.elalax.com  NOT AVAILABLE
3                             http://sch-hollywood.com/  NOT AVAILABLE
4                          http://www.khbaldwinpark.com  NOT AVAILABLE
...                                                 ...            ...
7591  https://www.adventisthealthcare.com/locations/...  NOT AVAILABLE
7592  https://cqch.org/cqch-clinics/copper-queen-dou...  NOT AVAILABLE
7593  https://portal.ct.gov/dmhas/wfh/whiting-forens...  NOT AVAILABLE
7594  https://aahs.org/locations/j--kent-mcnew-famil...  NOT AVAILABLE
7595          https://healthcare.utah.edu/orthopaedics/  NOT AVAILABLE

                                       ALT_NAME ST_FIPS               OWNER  \
0                                 NOT AVAILABLE       6         PROPRIETARY
1                                 NOT AVAILABLE       6         PROPRIETARY
2                                 NOT AVAILABLE       6         PROPRIETARY
3     HOLLYWOOD COMMUNITY HOSPITAL OF HOLLYWOOD       6         PROPRIETARY
4                                 NOT AVAILABLE       6         PROPRIETARY
...                                         ...     ...                 ...
7591                              NOT AVAILABLE      24          NON-PROFIT
7592                              NOT AVAILABLE       4          NON-PROFIT
7593                              NOT AVAILABLE       9  GOVERNMENT - STATE
7594                              NOT AVAILABLE      24          NON-PROFIT
7595                              NOT AVAILABLE      49  GOVERNMENT - STATE

     TTL_STAFF  BEDS         TRAUMA  HELIPAD
0         -999    49  NOT AVAILABLE        N
1         -999    62  NOT AVAILABLE        N
2         -999   127  NOT AVAILABLE        N
3         -999   100  NOT AVAILABLE        N
4         -999    95  NOT AVAILABLE        N
...        ...   ...            ...      ...
7591      -999   178  NOT AVAILABLE        N
7592      -999  -999       LEVEL IV        N
7593      -999   229  NOT AVAILABLE        N
7594      -999  -999  NOT AVAILABLE        N
7595      -999  -999  NOT AVAILABLE        N

[7596 rows x 34 columns]

In [19]:
hospital_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7596 entries, 0 to 7595
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           7596 non-null   float64
 1   Y           7596 non-null   float64
 2   OBJECTID    7596 non-null   int64
 3   ID          7596 non-null   int64
 4   NAME        7596 non-null   object
 5   ADDRESS     7596 non-null   object
 6   CITY        7596 non-null   object
 7   STATE       7596 non-null   object
 8   ZIP         7596 non-null   int64
 9   ZIP4        7596 non-null   object
 10  TELEPHONE   7596 non-null   object
 11  TYPE        7596 non-null   object
 12  STATUS      7596 non-null   object
 13  POPULATION  7596 non-null   int64
 14  COUNTY      7596 non-null   object
 15  COUNTYFIPS  7596 non-null   object
 16  COUNTRY     7596 non-null   object
 17  LATITUDE    7596 non-null   float64
 18  LONGITUDE   7596 non-null   float64
 19  NAICS_CODE  7596 non-null   int64
 20  NAICS_DESC  7596 non-null   object
 21  SOURCE      7596 non-null   object
 22  SOURCEDATE  7596 non-null   object
 23  VAL_METHOD  7596 non-null   object
 24  VAL_DATE    7596 non-null   object
 25  WEBSITE     7596 non-null   object
 26  STATE_ID    7596 non-null   object
 27  ALT_NAME    7596 non-null   object
 28  ST_FIPS     7596 non-null   int64
 29  OWNER       7596 non-null   object
 30  TTL_STAFF   7596 non-null   int64
 31  BEDS        7596 non-null   int64
 32  TRAUMA      7596 non-null   object
 33  HELIPAD     7596 non-null   object
dtypes: float64(4), int64(8), object(22)
memory usage: 2.0+ MB

In [20]:
hospital_df.head(10)

,X,Y,OBJECTID,ID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_DATE,WEBSITE,STATE_ID,ALT_NAME,ST_FIPS,OWNER,TTL_STAFF,BEDS,TRAUMA,HELIPAD
0,-1.331889e+07,4.346975e+06,1,5793230,CENTRAL VALLEY GENERAL HOSPITAL,1025 NORTH DOUTY STREET,HANFORD,CA,93230,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.hanfordhealth.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,49,NOT AVAILABLE,N
1,-1.322651e+07,4.049626e+06,2,53391362,LOS ROBLES HOSPITAL & MEDICAL CENTER - EAST CA...,150 VIA MERIDA,WESTLAKE VILAGE,CA,91362,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.losrobleshospital.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,62,NOT AVAILABLE,N
2,-1.315620e+07,4.031978e+06,3,11190023,EAST LOS ANGELES DOCTORS HOSPITAL,4060 WHITTIER BOULEVARD,LOS ANGELES,CA,90023,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.elalax.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,127,NOT AVAILABLE,N
3,-1.317190e+07,4.041752e+06,4,17090028,SOUTHERN CALIFORNIA HOSPITAL AT HOLLYWOOD,6245 DE LONGPRE AVENUE,HOLLYWOOD,CA,90028,NOT AVAILABLE,...,2014/02/10 00:00:00,http://sch-hollywood.com/,NOT AVAILABLE,HOLLYWOOD COMMUNITY HOSPITAL OF HOLLYWOOD,6,PROPRIETARY,-999,100,NOT AVAILABLE,N
4,-1.313208e+07,4.037270e+06,5,23691706,KINDRED HOSPITAL BALDWIN PARK,14148 FRANCISQUITO AVENUE,BALDWIN PARK,CA,91706,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.khbaldwinpark.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,95,NOT AVAILABLE,N
5,-1.315222e+07,4.009980e+06,6,25190712,LAKEWOOD REGIONAL MEDICAL CENTER,3700 EAST SOUTH STREET,LAKEWOOD,CA,90712,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.lakewoodregional.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,172,NOT AVAILABLE,N
6,-1.313488e+07,4.048794e+06,7,30791016,MONROVIA MEMORIAL HOSPITAL,323 SOUTH HELIOTROPE AVENUE,MONROVIA,CA,91016,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.monroviamemorial.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,49,NOT AVAILABLE,N
7,-1.315109e+07,4.035446e+06,8,30891754,MONTEREY PARK HOSPITAL,900 SOUTH ATLANTIC BOULEVARD,MONTEREY PARK,CA,91754,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.montereyparkhosp.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,101,NOT AVAILABLE,N
8,-1.317534e+07,4.005182e+06,9,47090505,STAR VIEW ADOLESCENT - P H F,4025 WEST 226 STREET,TORRANCE,CA,90505,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.starsinc.com/,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,16,NOT AVAILABLE,N
9,-1.308604e+07,4.009762e+06,10,9092879,CORONA REGIONAL MEDICAL CENTER-MAGNOLIA,730 MAGNOLIA AVENUE,CORONA,CA,92879,NOT AVAILABLE,...,2014/02/10 00:00:00,http://www.coronaregional.com,NOT AVAILABLE,NOT AVAILABLE,6,PROPRIETARY,-999,78,NOT AVAILABLE,N

In [28]:
hospital_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7596 entries, 0 to 7595
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           7596 non-null   float64
 1   Y           7596 non-null   float64
 2   OBJECTID    7596 non-null   int64
 3   ID          7596 non-null   int64
 4   NAME        7596 non-null   object
 5   ADDRESS     7596 non-null   object
 6   CITY        7596 non-null   object
 7   STATE       7596 non-null   object
 8   ZIP         7596 non-null   int64
 9   ZIP4        7596 non-null   object
 10  TELEPHONE   7596 non-null   object
 11  TYPE        7596 non-null   object
 12  STATUS      7596 non-null   object
 13  POPULATION  7596 non-null   int64
 14  COUNTY      7596 non-null   object
 15  COUNTYFIPS  7596 non-null   object
 16  COUNTRY     7596 non-null   object
 17  LATITUDE    7596 non-null   float64
 18  LONGITUDE   7596 non-null   float64
 19  NAICS_CODE  7596 non-null   int64
 20  NAICS_DESC  7596 non-null   object
 21  SOURCE      7596 non-null   object
 22  SOURCEDATE  7596 non-null   object
 23  VAL_METHOD  7596 non-null   object
 24  VAL_DATE    7596 non-null   object
 25  WEBSITE     7596 non-null   object
 26  STATE_ID    7596 non-null   object
 27  ALT_NAME    7596 non-null   object
 28  ST_FIPS     7596 non-null   int64
 29  OWNER       7596 non-null   object
 30  TTL_STAFF   7596 non-null   int64
 31  BEDS        7596 non-null   int64
 32  TRAUMA      7596 non-null   object
 33  HELIPAD     7596 non-null   object
dtypes: float64(4), int64(8), object(22)
memory usage: 2.0+ MB

In [36]:
new_hospital_df = hospital_df.drop(["X","Y","OBJECTID","ID","ZIP","ZIP4","TELEPHONE","STATUS","COUNTRY","NAICS_CODE","SOURCE","SOURCEDATE","VAL_METHOD","VAL_DATE","WEBSITE","STATE_ID","ALT_NAME","ST_FIPS","OWNER","TTL_STAFF","TRAUMA","HELIPAD"],axis=1)

In [34]:
hospital_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7596 entries, 0 to 7595
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           7596 non-null   float64
 1   Y           7596 non-null   float64
 2   OBJECTID    7596 non-null   int64
 3   ID          7596 non-null   int64
 4   NAME        7596 non-null   object
 5   ADDRESS     7596 non-null   object
 6   CITY        7596 non-null   object
 7   STATE       7596 non-null   object
 8   ZIP         7596 non-null   int64
 9   ZIP4        7596 non-null   object
 10  TELEPHONE   7596 non-null   object
 11  TYPE        7596 non-null   object
 12  STATUS      7596 non-null   object
 13  POPULATION  7596 non-null   int64
 14  COUNTY      7596 non-null   object
 15  COUNTYFIPS  7596 non-null   object
 16  COUNTRY     7596 non-null   object
 17  LATITUDE    7596 non-null   float64
 18  LONGITUDE   7596 non-null   float64
 19  NAICS_CODE  7596 non-null   int64
 20  NAICS_DESC  7596 non-null   object
 21  SOURCE      7596 non-null   object
 22  SOURCEDATE  7596 non-null   object
 23  VAL_METHOD  7596 non-null   object
 24  VAL_DATE    7596 non-null   object
 25  WEBSITE     7596 non-null   object
 26  STATE_ID    7596 non-null   object
 27  ALT_NAME    7596 non-null   object
 28  ST_FIPS     7596 non-null   int64
 29  OWNER       7596 non-null   object
 30  TTL_STAFF   7596 non-null   int64
 31  BEDS        7596 non-null   int64
 32  TRAUMA      7596 non-null   object
 33  HELIPAD     7596 non-null   object
dtypes: float64(4), int64(8), object(22)
memory usage: 2.0+ MB

In [37]:
new_hospital_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7596 entries, 0 to 7595
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NAME        7596 non-null   object
 1   ADDRESS     7596 non-null   object
 2   CITY        7596 non-null   object
 3   STATE       7596 non-null   object
 4   TYPE        7596 non-null   object
 5   POPULATION  7596 non-null   int64
 6   COUNTY      7596 non-null   object
 7   COUNTYFIPS  7596 non-null   object
 8   LATITUDE    7596 non-null   float64
 9   LONGITUDE   7596 non-null   float64
 10  NAICS_DESC  7596 non-null   object
 11  BEDS        7596 non-null   int64
dtypes: float64(2), int64(2), object(8)
memory usage: 712.2+ KB

In [39]:
new_hospital_df["TYPE"].value_counts()

GENERAL ACUTE CARE    4481
CRITICAL ACCESS       1027
PSYCHIATRIC            759
LONG TERM CARE         431
REHABILITATION         378
MILITARY               216
SPECIAL                145
CHILDREN               130
WOMEN                   20
CHRONIC DISEASE          9
Name: TYPE, dtype: int64

The most common type of hospital is General Acute Care

In [52]:
nashville_hospital = new_hospital_df.loc[(new_hospital_df["CITY"]=="NASHVILLE")]

In [58]:
nashville_tennessee_hospital = nashville_hospital.loc[nashville_hospital["STATE"]=="TN"]

In [59]:
print(nashville_tennessee_hospital)

                                               NAME  \
545                  TRISTAR SKYLINE MEDICAL CENTER
3449          SELECT SPECIALTY HOSPITAL - NASHVILLE
3485                           CURAHEALTH NASHVILLE
5429             THE WOMEN'S HOSPITAL AT CENTENNIAL
5433        METROPOLITAN NASHVILLE GENERAL HOSPITAL
6289                  SAINT THOMAS MIDTOWN HOSPITAL
6293  VANDERBILT STALLWORTH REHABILITATION HOSPITAL
6661           VA MEDICAL CENTER - NASHVILLE CAMPUS
6774    SAINT THOMAS HOSPITAL FOR SPECIALTY SURGERY
6777                     SAINT THOMAS WEST HOSPITAL
6786          TRISTAR SOUTHERN HILLS MEDICAL CENTER
6808              TRISTAR CENTENNIAL MEDICAL CENTER
6813                 VANDERBILT UNIVERSITY HOSPITAL

                             ADDRESS       CITY STATE                TYPE  \
545              3441 DICKERSON PIKE  NASHVILLE    TN  GENERAL ACUTE CARE
3449    2000 HAYES STREET, SUITE 500  NASHVILLE    TN      LONG TERM CARE
3485  1412 COUNTY HOSPITAL ROAD, B-1  NASHVILLE    TN      LONG TERM CARE
5429              2221 MURPHY AVENUE  NASHVILLE    TN               WOMEN
5433              1818 ALBION STREET  NASHVILLE    TN  GENERAL ACUTE CARE
6289              2000 CHURCH STREET  NASHVILLE    TN  GENERAL ACUTE CARE
6293             2201 CHILDREN'S WAY  NASHVILLE    TN      REHABILITATION
6661                 1310 24TH AVE S  NASHVILLE    TN            MILITARY
6774              2011 MURPHY AVENUE  NASHVILLE    TN  GENERAL ACUTE CARE
6777               4220 HARDING ROAD  NASHVILLE    TN  GENERAL ACUTE CARE
6786                391 WALLACE ROAD  NASHVILLE    TN  GENERAL ACUTE CARE
6808           2300 PATTERSON STREET  NASHVILLE    TN  GENERAL ACUTE CARE
6813       1211 MEDICAL CENTER DRIVE  NASHVILLE    TN  GENERAL ACUTE CARE

      POPULATION    COUNTY COUNTYFIPS   LATITUDE  LONGITUDE  \
545          213  DAVIDSON      47037  36.245341 -86.749619
3449          70  DAVIDSON      47037  36.152765 -86.801163
3485          60  DAVIDSON      47037  36.177468 -86.846124
5429        -999  DAVIDSON      47037  36.153665 -86.806831
5433         150  DAVIDSON      47037  36.166907 -86.806561
6289         683  DAVIDSON      47037  36.153908 -86.802006
6293          80  DAVIDSON      47037  36.138416 -86.802569
6661         493  DAVIDSON      47037  36.141757 -86.804239
6774          23  DAVIDSON      47037  36.155086 -86.803256
6777         541  DAVIDSON      47037  36.129402 -86.844516
6786         126  DAVIDSON      47037  36.076382 -86.721892
6808         733  DAVIDSON      47037  36.153752 -86.809005
6813        1091  DAVIDSON      47037  36.140836 -86.802167

                                             NAICS_DESC  BEDS
545              GENERAL MEDICAL AND SURGICAL HOSPITALS   213
3449  SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...    70
3485  SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...    60
5429  SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...  -999
5433             GENERAL MEDICAL AND SURGICAL HOSPITALS   150
6289             GENERAL MEDICAL AND SURGICAL HOSPITALS   683
6293  REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, D...    80
6661             GENERAL MEDICAL AND SURGICAL HOSPITALS   493
6774             GENERAL MEDICAL AND SURGICAL HOSPITALS    23
6777             GENERAL MEDICAL AND SURGICAL HOSPITALS   541
6786             GENERAL MEDICAL AND SURGICAL HOSPITALS   126
6808             GENERAL MEDICAL AND SURGICAL HOSPITALS   733
6813             GENERAL MEDICAL AND SURGICAL HOSPITALS  1091

In [60]:
nashville_tennessee_hospital

,NAME,ADDRESS,CITY,STATE,TYPE,POPULATION,COUNTY,COUNTYFIPS,LATITUDE,LONGITUDE,NAICS_DESC,BEDS
545,TRISTAR SKYLINE MEDICAL CENTER,3441 DICKERSON PIKE,NASHVILLE,TN,GENERAL ACUTE CARE,213,DAVIDSON,47037,36.245341,-86.749619,GENERAL MEDICAL AND SURGICAL HOSPITALS,213
3449,SELECT SPECIALTY HOSPITAL - NASHVILLE,"2000 HAYES STREET, SUITE 500",NASHVILLE,TN,LONG TERM CARE,70,DAVIDSON,47037,36.152765,-86.801163,SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...,70
3485,CURAHEALTH NASHVILLE,"1412 COUNTY HOSPITAL ROAD, B-1",NASHVILLE,TN,LONG TERM CARE,60,DAVIDSON,47037,36.177468,-86.846124,SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...,60
5429,THE WOMEN'S HOSPITAL AT CENTENNIAL,2221 MURPHY AVENUE,NASHVILLE,TN,WOMEN,-999,DAVIDSON,47037,36.153665,-86.806831,SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...,-999
5433,METROPOLITAN NASHVILLE GENERAL HOSPITAL,1818 ALBION STREET,NASHVILLE,TN,GENERAL ACUTE CARE,150,DAVIDSON,47037,36.166907,-86.806561,GENERAL MEDICAL AND SURGICAL HOSPITALS,150
6289,SAINT THOMAS MIDTOWN HOSPITAL,2000 CHURCH STREET,NASHVILLE,TN,GENERAL ACUTE CARE,683,DAVIDSON,47037,36.153908,-86.802006,GENERAL MEDICAL AND SURGICAL HOSPITALS,683
6293,VANDERBILT STALLWORTH REHABILITATION HOSPITAL,2201 CHILDREN'S WAY,NASHVILLE,TN,REHABILITATION,80,DAVIDSON,47037,36.138416,-86.802569,"REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, D...",80
6661,VA MEDICAL CENTER - NASHVILLE CAMPUS,1310 24TH AVE S,NASHVILLE,TN,MILITARY,493,DAVIDSON,47037,36.141757,-86.804239,GENERAL MEDICAL AND SURGICAL HOSPITALS,493
6774,SAINT THOMAS HOSPITAL FOR SPECIALTY SURGERY,2011 MURPHY AVENUE,NASHVILLE,TN,GENERAL ACUTE CARE,23,DAVIDSON,47037,36.155086,-86.803256,GENERAL MEDICAL AND SURGICAL HOSPITALS,23
6777,SAINT THOMAS WEST HOSPITAL,4220 HARDING ROAD,NASHVILLE,TN,GENERAL ACUTE CARE,541,DAVIDSON,47037,36.129402,-86.844516,GENERAL MEDICAL AND SURGICAL HOSPITALS,541
6786,TRISTAR SOUTHERN HILLS MEDICAL CENTER,391 WALLACE ROAD,NASHVILLE,TN,GENERAL ACUTE CARE,126,DAVIDSON,47037,36.076382,-86.721892,GENERAL MEDICAL AND SURGICAL HOSPITALS,126
6808,TRISTAR CENTENNIAL MEDICAL CENTER,2300 PATTERSON STREET,NASHVILLE,TN,GENERAL ACUTE CARE,733,DAVIDSON,47037,36.153752,-86.809005,GENERAL MEDICAL AND SURGICAL HOSPITALS,733
6813,VANDERBILT UNIVERSITY HOSPITAL,1211 MEDICAL CENTER DRIVE,NASHVILLE,TN,GENERAL ACUTE CARE,1091,DAVIDSON,47037,36.140836,-86.802167,GENERAL MEDICAL AND SURGICAL HOSPITALS,1091

The "BEDS" column is identical to the population column; it's possible that all of the beds are full, and would normally count the number of open beds there are at that location

In [79]:
tennessee_hospital = new_hospital_df.loc[new_hospital_df["STATE"]=="TN"]

In [80]:
tennessee_hospital

,NAME,ADDRESS,CITY,STATE,TYPE,POPULATION,COUNTY,COUNTYFIPS,LATITUDE,LONGITUDE,NAICS_DESC,BEDS
515,STARR REGIONAL MEDICAL CENTER ETOWAH,886 HIGHWAY 411 NORTH,ETOWAH,TN,GENERAL ACUTE CARE,72,MCMINN,47107,35.345099,-84.522719,GENERAL MEDICAL AND SURGICAL HOSPITALS,72
535,JACKSON COUNTY HOSPITAL,620 HOSPITAL DRIVE,GAINESBORO,TN,GENERAL ACUTE CARE,-999,JACKSON,47087,36.348807,-85.656244,GENERAL MEDICAL AND SURGICAL HOSPITALS,-999
536,MAURY REGIONAL HOSPITAL,1224 TROTWOOD AVENUE,COLUMBIA,TN,GENERAL ACUTE CARE,255,MAURY,47119,35.607164,-87.066891,GENERAL MEDICAL AND SURGICAL HOSPITALS,255
537,WEST TENNESSEE HEALTHCARE NORTH HOSPITAL,367 HOSPITAL BLVD.,JACKSON,TN,GENERAL ACUTE CARE,152,MADISON,47113,35.684447,-88.854048,GENERAL MEDICAL AND SURGICAL HOSPITALS,152
540,HENRY COUNTY MEDICAL CENTER,301 TYSON AVENUE,PARIS,TN,GENERAL ACUTE CARE,142,HENRY,47079,36.296543,-88.310305,GENERAL MEDICAL AND SURGICAL HOSPITALS,142
...,...,...,...,...,...,...,...,...,...,...,...,...
6810,TRISTAR PORTLAND MEDICAL PARK,105 RED BUD DR,PORTLAND,TN,GENERAL ACUTE CARE,159,SUMNER,47165,36.557292,-86.511620,GENERAL MEDICAL AND SURGICAL HOSPITALS,159
6811,TRISTAR STONECREST MEDICAL CENTER,200 STONECREST BOULEVARD,SMYRNA,TN,GENERAL ACUTE CARE,109,RUTHERFORD,47149,35.975034,-86.565202,GENERAL MEDICAL AND SURGICAL HOSPITALS,109
6812,UNICOI COUNTY MEMORIAL HOSPITAL,100 GREENWAY CIRCLE,ERWIN,TN,GENERAL ACUTE CARE,10,UNICOI,47171,36.133621,-82.413052,GENERAL MEDICAL AND SURGICAL HOSPITALS,10
6813,VANDERBILT UNIVERSITY HOSPITAL,1211 MEDICAL CENTER DRIVE,NASHVILLE,TN,GENERAL ACUTE CARE,1091,DAVIDSON,47037,36.140836,-86.802167,GENERAL MEDICAL AND SURGICAL HOSPITALS,1091
7362,UNICOI COUNTY HOSPITAL,2030 TEMPLE HILL ROAD,ERWIN,TN,GENERAL ACUTE CARE,10,UNICOI,47171,36.118445,-82.444649,GENERAL MEDICAL AND SURGICAL HOSPITALS,10

In [81]:
type(tennessee_hospital)

pandas.core.frame.DataFrame

In [84]:
tennessee_hospital["COUNTY"].value_counts()

SHELBY        23
DAVIDSON      15
HAMILTON      13
KNOX          11
WASHINGTON     6
              ..
HICKMAN        1
LAWRENCE       1
BENTON         1
HAYWOOD        1
TROUSDALE      1
Name: COUNTY, Length: 80, dtype: int64

Shelby County in TN has the most hospitals

In [94]:
tennessee_hospital["TYPE"].value_counts()

GENERAL ACUTE CARE    125
REHABILITATION         12
LONG TERM CARE         11
CRITICAL ACCESS         8
PSYCHIATRIC             5
MILITARY                4
CHILDREN                3
WOMEN                   3
Name: TYPE, dtype: int64

according to Google, 22 counties in TN have no hospitals, but   95-80+1 = 14(?) counties without hospitals

In [100]:
hospitals_df.shape

(7596, 34)

In [104]:
help(pd)

Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    =====================================================================

    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.

    Main Features
    -------------
    Here are just a few of the things that pandas does well:

      - Easy handling of missing data in floating point as well as non-floating
        point data.
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic and explicit data alignment: objects can be explicitly aligned
        to a set of labels, or the user can simply ignore the labels and let
        `Series`, `DataFrame`, etc. automatically align the data for you in
        computations.
      - Powerful, flexible group by functionality to perform split-apply-combine
        operations on data sets, for both aggregating and transforming data.
      - Make it easy to convert ragged, differently-indexed data in other Python
        and NumPy data structures into DataFrame objects.
      - Intelligent label-based slicing, fancy indexing, and subsetting of large
        data sets.
      - Intuitive merging and joining data sets.
      - Flexible reshaping and pivoting of data sets.
      - Hierarchical labeling of axes (possible to have multiple labels per tick).
      - Robust IO tools for loading data from flat files (CSV and delimited),
        Excel files, databases, and saving/loading data from the ultrafast HDF5
        format.
      - Time series-specific functionality: date range generation and frequency
        conversion, moving window statistics, date shifting and lagging.

PACKAGE CONTENTS
    _config (package)
    _libs (package)
    _testing
    _typing
    _version
    api (package)
    arrays (package)
    compat (package)
    conftest
    core (package)
    errors (package)
    io (package)
    plotting (package)
    testing
    tests (package)
    tseries (package)
    util (package)

SUBMODULES
    _hashtable
    _lib
    _tslib
    offsets

FUNCTIONS
    __getattr__(name)

DATA
    IndexSlice = <pandas.core.indexing._IndexSlice object>
    NA = <NA>
    NaT = NaT
    __docformat__ = 'restructuredtext'
    __git_version__ = '29d6b0232aab9576afa896ff5bab0b994760495a'
    describe_option = <pandas._config.config.CallableDynamicDoc object>
    get_option = <pandas._config.config.CallableDynamicDoc object>
    options = <pandas._config.config.DictWrapper object>
    reset_option = <pandas._config.config.CallableDynamicDoc object>
    set_option = <pandas._config.config.CallableDynamicDoc object>

VERSION
    1.0.1

FILE
    /opt/anaconda3/lib/python3.7/site-packages/pandas/__init__.py

In [106]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [107]:
new_hospital_df["TYPE"].unique()

array(['GENERAL ACUTE CARE', 'PSYCHIATRIC', 'CHILDREN', 'LONG TERM CARE',
       'CRITICAL ACCESS', 'REHABILITATION', 'MILITARY', 'WOMEN',
       'SPECIAL', 'CHRONIC DISEASE'], dtype=object)

In [108]:
help(pd.unique)

Help on function unique in module pandas.core.algorithms:

unique(values)
    Hash table-based unique. Uniques are returned in order
    of appearance. This does NOT sort.

    Significantly faster than numpy.unique. Includes NA values.

    Parameters
    ----------
    values : 1d array-like

    Returns
    -------
    numpy.ndarray or ExtensionArray

        The return can be:

        * Index : when the input is an Index
        * Categorical : when the input is a Categorical dtype
        * ndarray : when the input is a Series/ndarray

        Return numpy.ndarray or ExtensionArray.

    See Also
    --------
    Index.unique
    Series.unique

    Examples
    --------
    >>> pd.unique(pd.Series([2, 1, 3, 3]))
    array([2, 1, 3])

    >>> pd.unique(pd.Series([2] + [1] * 5))
    array([2, 1])

    >>> pd.unique(pd.Series([pd.Timestamp('20160101'),
    ...                     pd.Timestamp('20160101')]))
    array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

    >>> pd.unique(pd.Series([pd.Timestamp('20160101', tz='US/Eastern'),
    ...                      pd.Timestamp('20160101', tz='US/Eastern')]))
    array([Timestamp('2016-01-01 00:00:00-0500', tz='US/Eastern')],
          dtype=object)

    >>> pd.unique(pd.Index([pd.Timestamp('20160101', tz='US/Eastern'),
    ...                     pd.Timestamp('20160101', tz='US/Eastern')]))
    DatetimeIndex(['2016-01-01 00:00:00-05:00'],
    ...           dtype='datetime64[ns, US/Eastern]', freq=None)

    >>> pd.unique(list('baabc'))
    array(['b', 'a', 'c'], dtype=object)

    An unordered Categorical will return categories in the
    order of appearance.

    >>> pd.unique(pd.Series(pd.Categorical(list('baabc'))))
    [b, a, c]
    Categories (3, object): [b, a, c]

    >>> pd.unique(pd.Series(pd.Categorical(list('baabc'),
    ...                                    categories=list('abc'))))
    [b, a, c]
    Categories (3, object): [b, a, c]

    An ordered Categorical preserves the category ordering.

    >>> pd.unique(pd.Series(pd.Categorical(list('baabc'),
    ...                                    categories=list('abc'),
    ...                                    ordered=True)))
    [b, a, c]
    Categories (3, object): [a < b < c]

    An array of tuples

    >>> pd.unique([('a', 'b'), ('b', 'a'), ('a', 'c'), ('b', 'a')])
    array([('a', 'b'), ('b', 'a'), ('a', 'c')], dtype=object)

In [112]:
new_hospital_df.loc[(new_hospital_df["CITY"]=="NASHVILLE")&(new_hospital_df["STATE"]=="TN")]

,NAME,ADDRESS,CITY,STATE,TYPE,POPULATION,COUNTY,COUNTYFIPS,LATITUDE,LONGITUDE,NAICS_DESC,BEDS
545,TRISTAR SKYLINE MEDICAL CENTER,3441 DICKERSON PIKE,NASHVILLE,TN,GENERAL ACUTE CARE,213,DAVIDSON,47037,36.245341,-86.749619,GENERAL MEDICAL AND SURGICAL HOSPITALS,213
3449,SELECT SPECIALTY HOSPITAL - NASHVILLE,"2000 HAYES STREET, SUITE 500",NASHVILLE,TN,LONG TERM CARE,70,DAVIDSON,47037,36.152765,-86.801163,SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...,70
3485,CURAHEALTH NASHVILLE,"1412 COUNTY HOSPITAL ROAD, B-1",NASHVILLE,TN,LONG TERM CARE,60,DAVIDSON,47037,36.177468,-86.846124,SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...,60
5429,THE WOMEN'S HOSPITAL AT CENTENNIAL,2221 MURPHY AVENUE,NASHVILLE,TN,WOMEN,-999,DAVIDSON,47037,36.153665,-86.806831,SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE AB...,-999
5433,METROPOLITAN NASHVILLE GENERAL HOSPITAL,1818 ALBION STREET,NASHVILLE,TN,GENERAL ACUTE CARE,150,DAVIDSON,47037,36.166907,-86.806561,GENERAL MEDICAL AND SURGICAL HOSPITALS,150
6289,SAINT THOMAS MIDTOWN HOSPITAL,2000 CHURCH STREET,NASHVILLE,TN,GENERAL ACUTE CARE,683,DAVIDSON,47037,36.153908,-86.802006,GENERAL MEDICAL AND SURGICAL HOSPITALS,683
6293,VANDERBILT STALLWORTH REHABILITATION HOSPITAL,2201 CHILDREN'S WAY,NASHVILLE,TN,REHABILITATION,80,DAVIDSON,47037,36.138416,-86.802569,"REHABILITATION HOSPITALS (EXCEPT ALCOHOLISM, D...",80
6661,VA MEDICAL CENTER - NASHVILLE CAMPUS,1310 24TH AVE S,NASHVILLE,TN,MILITARY,493,DAVIDSON,47037,36.141757,-86.804239,GENERAL MEDICAL AND SURGICAL HOSPITALS,493
6774,SAINT THOMAS HOSPITAL FOR SPECIALTY SURGERY,2011 MURPHY AVENUE,NASHVILLE,TN,GENERAL ACUTE CARE,23,DAVIDSON,47037,36.155086,-86.803256,GENERAL MEDICAL AND SURGICAL HOSPITALS,23
6777,SAINT THOMAS WEST HOSPITAL,4220 HARDING ROAD,NASHVILLE,TN,GENERAL ACUTE CARE,541,DAVIDSON,47037,36.129402,-86.844516,GENERAL MEDICAL AND SURGICAL HOSPITALS,541
6786,TRISTAR SOUTHERN HILLS MEDICAL CENTER,391 WALLACE ROAD,NASHVILLE,TN,GENERAL ACUTE CARE,126,DAVIDSON,47037,36.076382,-86.721892,GENERAL MEDICAL AND SURGICAL HOSPITALS,126
6808,TRISTAR CENTENNIAL MEDICAL CENTER,2300 PATTERSON STREET,NASHVILLE,TN,GENERAL ACUTE CARE,733,DAVIDSON,47037,36.153752,-86.809005,GENERAL MEDICAL AND SURGICAL HOSPITALS,733
6813,VANDERBILT UNIVERSITY HOSPITAL,1211 MEDICAL CENTER DRIVE,NASHVILLE,TN,GENERAL ACUTE CARE,1091,DAVIDSON,47037,36.140836,-86.802167,GENERAL MEDICAL AND SURGICAL HOSPITALS,1091

In [114]:
tennessee_hospital["COUNTY"].nunique()

80